#!/bin/bash
# don't allow pushing to master branch

hook_name="hooks/$(basename $0)"
cur_branch=$(git name-rev --name-only --no-undefined --always HEAD)
push_cmd=$(ps --pid $PPID --format "command=")

protected_branches="^(master|main|trunk)"
affirmative="yes|y|Y"

# putting regexes in quotes makes them fail, because bash ¯\_(ツ)_/¯
if [[ "$cur_branch" =~ $protected_branches ]]; then
    echo -ne "${hook_name}: are you aware that you are on branch ${cur_branch}? "
    read confirmation < /dev/tty
    if [[ ! "$confirmation" =~ $affirmative ]]; then
        exit 2
    fi
fi
exit 0